FROM node:22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache curl

ENV HUSKY=0
ENV CI=true

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_API_BASE_URL
ARG APP_SERVER_URL
ARG APP_CLIENT_URL
ARG LOGO_SMALL_URL
ARG LOGO_LARGE_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV APP_SERVER_URL=$APP_SERVER_URL
ENV APP_CLIENT_URL=$APP_CLIENT_URL
ENV LOGO_SMALL_URL=$LOGO_SMALL_URL
ENV LOGO_LARGE_URL=$LOGO_LARGE_URL

RUN npm run build


FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY --from=builder /app/.output ./.output
COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh && \
    addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nitro && \
    chown nitro:nodejs /docker-entrypoint.sh && \
    chown -R nitro:nodejs /app

USER nitro

EXPOSE 3000
ENV PORT=3000

# ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["node", ".output/server/index.mjs"]
