name: develop-lowcodejs

services:
  develop-mongo:
    image: mongo:latest
    container_name: develop-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: develop
      MONGO_INITDB_ROOT_PASSWORD: develop
    volumes:
      - develop-mongo-volume:/data/db
    ports:
      - "27012:27017"
    networks:
      - traefik-network

  develop-api:
    container_name: develop-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env.develop
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - develop-storage-api-volume:/app/_storage
    depends_on:
      - develop-mongo
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"

      # HTTPS (principal)
      - "traefik.http.routers.develop-api.rule=Host(`api.develop.lowcodejs.org`)"
      - "traefik.http.routers.develop-api.entrypoints=websecure"
      - "traefik.http.routers.develop-api.tls.certresolver=myresolver"
      - "traefik.http.services.develop-api.loadbalancer.server.port=3000"

      # HTTP para HTTPS redirect
      - "traefik.http.routers.develop-api-http.rule=Host(`api.develop.lowcodejs.org`)"
      - "traefik.http.routers.develop-api-http.entrypoints=web"
      - "traefik.http.routers.develop-api-http.middlewares=https-only@file"

      # Retry middleware
      - "traefik.http.routers.develop-api.middlewares=develop-api-retry"
      - "traefik.http.middlewares.develop-api-retry.retry.attempts=3"
      - "traefik.http.middlewares.develop-api-retry.retry.initialinterval=500ms"

      # Sticky sessions
      - "traefik.http.services.develop-api.loadbalancer.sticky.cookie=true"

  develop-app:
    container_name: develop-app
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env.develop
    environment:
      - VITE_API_BASE_URL="https://api.develop.lowcodejs.org"
    depends_on:
      - develop-api
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      # HTTPS (principal)
      - "traefik.http.routers.develop-app.rule=Host(`develop.lowcodejs.org`)"
      - "traefik.http.routers.develop-app.entrypoints=websecure"
      - "traefik.http.routers.develop-app.tls.certresolver=myresolver"
      - "traefik.http.services.develop-app.loadbalancer.server.port=80"
      # HTTP para HTTPS redirect
      - "traefik.http.routers.develop-app-http.rule=Host(`develop.lowcodejs.org`)"
      - "traefik.http.routers.develop-app-http.entrypoints=web"
      - "traefik.http.routers.develop-app-http.middlewares=https-only@file"

volumes:
  develop-mongo-volume:
    driver: local
  develop-storage-api-volume:
    driver: local

networks:
  traefik-network:
    external: true
