name: demo-lowcodejs

services:
  demo-mongo:
    image: mongo:latest
    container_name: demo-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: demo
      MONGO_INITDB_ROOT_PASSWORD: demo
    volumes:
      - demo-mongo-volume:/data/db
    ports:
      - "27012:27017"
    networks:
      - demo-lowcodejs-network

  demo-api:
    container_name: demo-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env.demo
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - demo-storage-api-volume:/app/_storage
    depends_on:
      - demo-mongo
    networks:
      - demo-lowcodejs-network
      - traefik-network
    labels:
      - "traefik.enable=true"

      # HTTPS (principal)
      - "traefik.http.routers.demo-api.rule=Host(`api.demo.lowcodejs.org`)"
      - "traefik.http.routers.demo-api.entrypoints=websecure"
      - "traefik.http.routers.demo-api.tls.certresolver=myresolver"
      - "traefik.http.services.demo-api.loadbalancer.server.port=3000"

      # HTTP para HTTPS redirect
      - "traefik.http.routers.demo-api-http.rule=Host(`api.demo.lowcodejs.org`)"
      - "traefik.http.routers.demo-api-http.entrypoints=web"
      - "traefik.http.routers.demo-api-http.middlewares=https-only@file"

      # Retry middleware
      - "traefik.http.routers.demo-api.middlewares=demo-api-retry"
      - "traefik.http.middlewares.demo-api-retry.retry.attempts=3"
      - "traefik.http.middlewares.demo-api-retry.retry.initialinterval=500ms"

      # Sticky sessions
      - "traefik.http.services.demo-api.loadbalancer.sticky.cookie=true"

  demo-app:
    container_name: demo-app
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://api.demo.lowcodejs.org
    env_file:
      - ./app/.env.demo
    ports:
      - "5172:80"
    depends_on:
      - demo-api
    networks:
      - demo-lowcodejs-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      # HTTPS (principal)
      - "traefik.http.routers.demo-app.rule=Host(`demo.lowcodejs.org`)"
      - "traefik.http.routers.demo-app.entrypoints=websecure"
      - "traefik.http.routers.demo-app.tls.certresolver=myresolver"
      - "traefik.http.services.demo-app.loadbalancer.server.port=80"
      # HTTP para HTTPS redirect
      - "traefik.http.routers.demo-app-http.rule=Host(`demo.lowcodejs.org`)"
      - "traefik.http.routers.demo-app-http.entrypoints=web"
      - "traefik.http.routers.demo-app-http.middlewares=https-only@file"

volumes:
  demo-mongo-volume:
    driver: local
  demo-storage-api-volume:
    driver: local

networks:
  demo-lowcodejs-network:
    driver: bridge
  traefik-network:
    external: true
