FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl curl

COPY package*.json ./

RUN npm install

COPY . .

# RUN npx prisma generate

# Seed deve rodar após os containers subirem:
# docker exec low-code-js-backend npm run seed

EXPOSE 3000

CMD ["npm", "run", "dev"]