FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache openssl curl su-exec

COPY package*.json ./

RUN npm install

COPY . .

COPY docker-entry-point.sh /docker-entry-point.sh
RUN chmod +x /docker-entry-point.sh

EXPOSE 3000

ENTRYPOINT ["/docker-entry-point.sh"]
CMD ["npm", "run", "dev"]
