FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache openssl curl su-exec

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x /app/docker-entry-point.sh

EXPOSE 3000

ENTRYPOINT ["/app/docker-entry-point.sh"]
CMD ["npm", "run", "dev"]
