erDiagram
  USER }o--o| USER_GROUP : group
  USER_GROUP }o--o{ PERMISSION : permissions
  TABLE }o--|| USER : owner
  TABLE }o--o{ USER : administrators
  TABLE ||--o{ FIELD : fields
  TABLE }o--o| STORAGE : logo
  FIELD }o--o| TABLE : relationship
  FIELD }o--o| FIELD : group
  VALIDATION_TOKEN }o--|| USER : user
  MENU }o--o| TABLE : table
  MENU }o--o| MENU : parent
  MENU }o--o| USER : owner
  REACTION }o--o| USER : user
  EVALUATION }o--o| USER : user
  SETTING }o--o{ TABLE : model_clone_tables
  NOTIFICATION }o--|| USER : userId
  NOTIFICATION }o--o| USER : actorUserId
  LOGGER }o--o| USER : user
  ROW }o--o| USER : creator
  ROW }o--o{ STORAGE : file_fields
  ROW }o--o{ TABLE : relationship_fields
