networks:
  traefik-network:
    external: true

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile.demo
    container_name: demo-app
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      # HTTPS (principal)
      - "traefik.http.routers.demo-app.rule=Host(`demo.lowcodejs.org`)"
      - "traefik.http.routers.demo-app.entrypoints=websecure"
      - "traefik.http.routers.demo-app.tls.certresolver=myresolver"
      - "traefik.http.services.demo-app.loadbalancer.server.port=80"
      # HTTP para HTTPS redirect
      - "traefik.http.routers.demo-app-http.rule=Host(`demo.lowcodejs.org`)"
      - "traefik.http.routers.demo-app-http.entrypoints=web"
      - "traefik.http.routers.demo-app-http.middlewares=https-only@file"
