networks:
  traefik-network:
    external: true

services:
  develop-app:
    build:
      context: .
      dockerfile: Dockerfile.develop
    container_name: develop-app
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      # HTTPS (principal)
      - "traefik.http.routers.develop-app.rule=Host(`develop.lowcodejs.org`)"
      - "traefik.http.routers.develop-app.entrypoints=websecure"
      - "traefik.http.routers.develop-app.tls.certresolver=myresolver"
      - "traefik.http.services.develop-app.loadbalancer.server.port=80"
      # HTTP para HTTPS redirect
      - "traefik.http.routers.develop-app-http.rule=Host(`develop.lowcodejs.org`)"
      - "traefik.http.routers.develop-app-http.entrypoints=web"
      - "traefik.http.routers.develop-app-http.middlewares=https-only@file"
