export const KANBAN_TEMPLATE_ID = 'KANBAN_TEMPLATE';
export const CARDS_TEMPLATE_ID = 'CARDS_TEMPLATE';
export const MOSAIC_TEMPLATE_ID = 'MOSAIC_TEMPLATE';
export const DOCUMENT_TEMPLATE_ID = 'DOCUMENT_TEMPLATE';
export const FORUM_TEMPLATE_ID = 'FORUM_TEMPLATE';
export const CALENDAR_TEMPLATE_ID = 'CALENDAR_TEMPLATE';
