/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { LinkProps } from "@tanstack/react-router";

/**
 * Make some property optional an type
 *
 * @example
 * ```typescript
 * type Post {
 *  id: string;
 *  name: string;
 *  email: string;
 * }
 *
 * Optional<Post, 'name' | 'email>
 * ```
 */
export type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;

export type Locale = "pt-br" | "en-us";

export const APP_ID = "@LOWCODEJS:V1";

export type Translation = {
  // GLOBAL - Global Components
  GLOBAL_ACTION_LABEL: string;
  GLOBAL_ACTION_SHOW_LABEL: string;
  GLOBAL_ACTION_UPDATE_LABEL: string;
  GLOBAL_ACTION_DELETE_LABEL: string;
  GLOBAL_ACTION_SHARE_LABEL: string;
  GLOBAL_ACTION_INTERNAL_LABEL: string;
  GLOBAL_ACTION_RESTORE_LABEL: string;
  GLOBAL_ACTION_VIEW_LABEL: string;
  GLOBAL_ACTION_EDIT_LABEL: string;
  GLOBAL_ACTION_REMOVE_LABEL: string;
  GLOBAL_ACTION_ADD_LABEL: string;

  GLOBAL_BUTTON_UPDATE_LABEL: string;
  GLOBAL_BUTTON_CREATE_LABEL: string;
  GLOBAL_BUTTON_CLEAR_LABEL: string;
  GLOBAL_BUTTON_SEARCH_LABEL: string;
  GLOBAL_BUTTON_CANCEL_LABEL: string;
  GLOBAL_BUTTON_CONFIRM_LABEL: string;
  GLOBAL_BUTTON_SAVE_LABEL: string;
  GLOBAL_BUTTON_CLOSE_LABEL: string;
  GLOBAL_BUTTON_EXIT_LABEL: string;
  GLOBAL_BUTTON_ADD_LABEL: string;
  GLOBAL_BUTTON_LOGOUT_LABEL: string;

  GLOBAL_INPUT_SEARCH_PLACEHOLDER: string;
  GLOBAL_SELECT_PLACEHOLDER: string;
  GLOBAL_SELECT_DEFAULT_PLACEHOLDER: string;

  GLOBAL_PAGINATION_PER_PAGE_LABEL: string;
  GLOBAL_PAGINATION_PAGE_LABEL: string;
  GLOBAL_PAGINATION_GO_PREVIOUS_PAGE: string;
  GLOBAL_PAGINATION_GO_NEXT_PAGE: string;

  GLOBAL_ERROR_INVALID_PARAMETERS: string;
  GLOBAL_ERROR_AUTHENTICATION_REQUIRED: string;
  GLOBAL_ERROR_ACCESS_DENIED: string;
  GLOBAL_ERROR_SERVER_ERROR: string;
  GLOBAL_ERROR_RATE_LIMIT_EXCEEDED: string;
  GLOBAL_ERROR_FILE_ERROR: string;
  GLOBAL_ERROR_FILE_TOO_BIG: string;
  GLOBAL_ERROR_FILE_TYPE_NOT_ALLOWED: string;
  GLOBAL_ERROR_UPLOAD_LIMIT_EXCEEDED: string;
  GLOBAL_ERROR_STORAGE_QUOTA_EXCEEDED: string;
  GLOBAL_ERROR_INVALID_FILE_ID: string;
  GLOBAL_ERROR_FILE_NOT_FOUND: string;

  GLOBAL_SUCCESS_CREATED: string;
  GLOBAL_SUCCESS_UPDATED: string;
  GLOBAL_SUCCESS_DELETED: string;
  GLOBAL_SUCCESS_RESTORED: string;
  GLOBAL_SUCCESS_SETTINGS_UPDATED: string;

  GLOBAL_STATUS_NA: string;
  GLOBAL_LOADING: string;
  GLOBAL_MENU_LABEL: string;
  GLOBAL_CONFIGURATIONS_LABEL: string;

  GLOBAL_ACCESSIBILITY_BREADCRUMB: string;
  GLOBAL_ACCESSIBILITY_PAGINATION: string;
  GLOBAL_ACCESSIBILITY_TOGGLE_SIDEBAR: string;

  // SIDEBAR - Sidebar Navigation
  SIDEBAR_MENU_HOME_LABEL: string;
  SIDEBAR_MENU_COLLECTION_LABEL: string;
  SIDEBAR_MENU_DASHBOARD_LABEL: string;
  SIDEBAR_MENU_CONFIGURATION_USER_LABEL: string;
  SIDEBAR_MENU_CONFIGURATION_USER_GROUP_LABEL: string;
  SIDEBAR_MENU_CONFIGURATION_SYSTEM_LABEL: string;
  SIDEBAR_MENU_LOGOUT_LABEL: string;

  // HEADER - Header Components
  HEADER_PROFILE_DROPDOWN_USER_AVATAR_ALT: string;
  HEADER_PROFILE_DROPDOWN_PROFILE_MENU_ITEM: string;
  HEADER_PROFILE_DROPDOWN_LOGOUT_MENU_ITEM: string;

  // AUTH_SIGNIN - Authentication Sign In
  AUTH_SIGNIN_PAGE_TITLE: string;
  AUTH_SIGNIN_EMAIL_LABEL: string;
  AUTH_SIGNIN_EMAIL_PLACEHOLDER: string;
  AUTH_SIGNIN_PASSWORD_LABEL: string;
  AUTH_SIGNIN_PASSWORD_PLACEHOLDER: string;
  AUTH_SIGNIN_FORGOT_PASSWORD_LINK: string;
  AUTH_SIGNIN_REGISTER_LINK: string;
  AUTH_SIGNIN_LOGIN_BUTTON: string;
  AUTH_SIGNIN_ERROR_INVALID_CREDENTIALS: string;
  AUTH_SIGNIN_ERROR_USER_INACTIVE: string;

  // AUTH_SIGNUP - Authentication Sign Up
  AUTH_SIGNUP_PAGE_TITLE: string;
  AUTH_SIGNUP_PAGE_DESCRIPTION: string;
  AUTH_SIGNUP_EMAIL_LABEL: string;
  AUTH_SIGNUP_EMAIL_PLACEHOLDER: string;
  AUTH_SIGNUP_NAME_LABEL: string;
  AUTH_SIGNUP_NAME_PLACEHOLDER: string;
  AUTH_SIGNUP_PASSWORD_LABEL: string;
  AUTH_SIGNUP_PASSWORD_PLACEHOLDER: string;
  AUTH_SIGNUP_CONFIRM_PASSWORD_LABEL: string;
  AUTH_SIGNUP_CONFIRM_PASSWORD_PLACEHOLDER: string;
  AUTH_SIGNUP_HAVE_ACCOUNT_LINK: string;
  AUTH_SIGNUP_REGISTER_BUTTON: string;

  // AUTH_SUCCESS - Authentication Success
  AUTH_SUCCESS_PAGE_TITLE: string;
  AUTH_SUCCESS_PAGE_DESCRIPTION: string;
  AUTH_SUCCESS_LOGIN_BUTTON: string;

  // PASSWORD_RECOVERY - Password Recovery
  PASSWORD_RECOVERY_REQUEST_CODE_TITLE: string;
  PASSWORD_RECOVERY_REQUEST_CODE_DESCRIPTION: string;
  PASSWORD_RECOVERY_EMAIL_LABEL: string;
  PASSWORD_RECOVERY_EMAIL_PLACEHOLDER: string;
  PASSWORD_RECOVERY_SEND_CODE_BUTTON: string;
  PASSWORD_RECOVERY_VALIDATE_CODE_TITLE: string;
  PASSWORD_RECOVERY_VALIDATE_CODE_DESCRIPTION: string;
  PASSWORD_RECOVERY_VERIFICATION_CODE_LABEL: string;
  PASSWORD_RECOVERY_CONFIRM_BUTTON: string;
  PASSWORD_RECOVERY_RESET_TITLE: string;
  PASSWORD_RECOVERY_RESET_DESCRIPTION: string;
  PASSWORD_RECOVERY_NEW_PASSWORD_LABEL: string;
  PASSWORD_RECOVERY_CONFIRM_NEW_PASSWORD_LABEL: string;
  PASSWORD_RECOVERY_SUCCESS_TITLE: string;
  PASSWORD_RECOVERY_SUCCESS_DESCRIPTION: string;
  PASSWORD_RECOVERY_SUCCESS_LOGIN_BUTTON: string;

  // DASHBOARD - Dashboard Route
  DASHBOARD_ROUTE_TITLE: string;
  DASHBOARD_ROUTE_DESCRIPTION: string;

  // USER_ROUTE - Users Route
  USER_ROUTE_TITLE: string;
  USER_ROUTE_CREATE_LABEL: string;
  USER_ROUTE_TABLE_HEADERS: string;

  // USER_SHEET - User Sheets
  USER_SHEET_SHOW_TITLE: string;
  USER_SHEET_SHOW_DESCRIPTION: string;
  USER_SHEET_CREATE_TITLE: string;
  USER_SHEET_CREATE_DESCRIPTION: string;
  USER_SHEET_UPDATE_TITLE: string;
  USER_SHEET_UPDATE_DESCRIPTION: string;

  // USER_FORM - User Form Fields
  USER_FORM_FIELD_NAME_LABEL: string;
  USER_FORM_FIELD_NAME_PLACEHOLDER: string;
  USER_FORM_FIELD_EMAIL_LABEL: string;
  USER_FORM_FIELD_EMAIL_PLACEHOLDER: string;
  USER_FORM_FIELD_ROLE_LABEL: string;
  USER_FORM_FIELD_ROLE_PLACEHOLDER: string;
  USER_FORM_FIELD_PASSWORD_LABEL: string;
  USER_FORM_FIELD_PASSWORD_PLACEHOLDER: string;
  USER_FORM_FIELD_STATUS_LABEL: string;
  USER_FORM_FIELD_STATUS_DESCRIPTION: string;
  USER_FORM_FIELD_STATUS_ACTIVE_OPTION: string;
  USER_FORM_FIELD_STATUS_INACTIVE_OPTION: string;
  USER_FORM_FIELD_GROUP_LABEL: string;
  USER_FORM_FIELD_GROUP_PLACEHOLDER: string;

  // USER_VALIDATION - User Validation Messages
  USER_VALIDATION_NAME_REQUIRED: string;
  USER_VALIDATION_EMAIL_REQUIRED: string;
  USER_VALIDATION_EMAIL_INVALID: string;
  USER_VALIDATION_EMAIL_EXISTS: string;
  USER_VALIDATION_PASSWORD_REQUIRED: string;
  USER_VALIDATION_GROUP_REQUIRED: string;

  // USER_GROUP_ROUTE - User Groups Route
  USER_GROUP_ROUTE_TITLE: string;
  USER_GROUP_ROUTE_CREATE_LABEL: string;
  USER_GROUP_ROUTE_TABLE_HEADERS: string;

  // USER_GROUP_SHEET - User Group Sheets
  USER_GROUP_SHEET_SHOW_TITLE: string;
  USER_GROUP_SHEET_SHOW_DESCRIPTION: string;
  USER_GROUP_SHEET_CREATE_TITLE: string;
  USER_GROUP_SHEET_CREATE_DESCRIPTION: string;
  USER_GROUP_SHEET_UPDATE_TITLE: string;
  USER_GROUP_SHEET_UPDATE_DESCRIPTION: string;

  // USER_GROUP_FORM - User Group Form Fields
  USER_GROUP_FORM_FIELD_NAME_LABEL: string;
  USER_GROUP_FORM_FIELD_NAME_PLACEHOLDER: string;
  USER_GROUP_FORM_FIELD_DESCRIPTION_LABEL: string;
  USER_GROUP_FORM_FIELD_DESCRIPTION_PLACEHOLDER: string;
  USER_GROUP_FORM_FIELD_PERMISSIONS_LABEL: string;
  USER_GROUP_FORM_FIELD_PERMISSIONS_DESCRIPTION: string;

  // USER_GROUP_VALIDATION - User Group Validation Messages
  USER_GROUP_VALIDATION_NAME_REQUIRED: string;
  USER_GROUP_VALIDATION_DESCRIPTION_REQUIRED: string;
  USER_GROUP_VALIDATION_PERMISSIONS_REQUIRED: string;

  // COLLECTION_ROUTE - Collections Route
  COLLECTION_ROUTE_TITLE: string;
  COLLECTION_ROUTE_CREATE_LABEL: string;
  COLLECTION_ROUTE_TABLE_HEADERS: string;

  // COLLECTION_SHEET - Collection Sheets
  COLLECTION_SHEET_FILTER_TITLE: string;
  COLLECTION_SHEET_FILTER_DESCRIPTION: string;
  COLLECTION_SHEET_SHOW_TITLE: string;
  COLLECTION_SHEET_SHOW_DESCRIPTION: string;
  COLLECTION_SHEET_CREATE_TITLE: string;
  COLLECTION_SHEET_CREATE_DESCRIPTION: string;
  COLLECTION_SHEET_UPDATE_TITLE: string;
  COLLECTION_SHEET_UPDATE_DESCRIPTION: string;

  // COLLECTION_BUTTON - Collection Buttons
  COLLECTION_BUTTON_TRASH_LABEL: string;
  COLLECTION_BUTTON_FILTER_LABEL: string;
  COLLECTION_BUTTON_STYLE_LABEL: string;

  // COLLECTION_FORM - Collection Form Fields
  COLLECTION_FORM_FIELD_LOGO_LABEL: string;
  COLLECTION_FORM_FIELD_LOGO_PLACEHOLDER: string;
  COLLECTION_FORM_FIELD_NAME_LABEL: string;
  COLLECTION_FORM_FIELD_NAME_PLACEHOLDER: string;
  COLLECTION_FORM_FIELD_DESCRIPTION_LABEL: string;
  COLLECTION_FORM_FIELD_DESCRIPTION_PLACEHOLDER: string;
  COLLECTION_FORM_FIELD_LAYOUT_LABEL: string;
  COLLECTION_FORM_FIELD_LAYOUT_DESCRIPTION: string;
  COLLECTION_FORM_FIELD_VISIBILITY_LABEL: string;
  COLLECTION_FORM_FIELD_VISIBILITY_RESTRICTED_OPTION: string;
  COLLECTION_FORM_FIELD_VISIBILITY_PUBLIC_OPTION: string;
  COLLECTION_FORM_FIELD_COLLABORATION_LABEL: string;
  COLLECTION_FORM_FIELD_COLLABORATION_OPEN_OPTION: string;
  COLLECTION_FORM_FIELD_COLLABORATION_RESTRICTED_OPTION: string;
  COLLECTION_FORM_FIELD_ADMINISTRATOR_LABEL: string;

  // COLLECTION_DROPDOWN - Collection Dropdowns
  COLLECTION_DROPDOWN_LAYOUT_LABEL: string;
  COLLECTION_DROPDOWN_CONFIGURATION_LABEL: string;
  COLLECTION_DROPDOWN_CONFIGURATION_MANAGE_FIELDS_OPTION: string;

  // COLLECTION_LAYOUT - Collection Layout
  COLLECTION_LAYOUT_LIST_LABEL: string;
  COLLECTION_LAYOUT_GRID_LABEL: string;

  // COLLECTION_VALIDATION - Collection Validation Messages
  COLLECTION_VALIDATION_NAME_REQUIRED: string;
  COLLECTION_VALIDATION_NAME_EXISTS: string;
  COLLECTION_VALIDATION_DESCRIPTION_REQUIRED: string;

  // COLLECTION_INTERNAL - Collection Internal
  COLLECTION_INTERNAL_TYPE_LABEL: string;
  COLLECTION_INTERNAL_NUMBER_LABEL: string;

  // COLLECTION_ROW_SHEET - Collection Row Sheets
  COLLECTION_ROW_SHEET_FILTER_TITLE: string;
  COLLECTION_ROW_SHEET_FILTER_DESCRIPTION: string;
  COLLECTION_ROW_SHEET_CREATE_TITLE: string;
  COLLECTION_ROW_SHEET_CREATE_DESCRIPTION: string;
  COLLECTION_ROW_SHEET_UPDATE_TITLE: string;
  COLLECTION_ROW_SHEET_UPDATE_DESCRIPTION: string;
  COLLECTION_ROW_SHEET_SHOW_TITLE: string;
  COLLECTION_ROW_SHEET_SHOW_DESCRIPTION: string;

  // COLLECTION_ROW_BUTTON - Collection Row Buttons
  COLLECTION_ROW_BUTTON_CREATE_LABEL: string;
  COLLECTION_ROW_BUTTON_ADD_LABEL: string;

  // COLLECTION_ROW_VALIDATION - Collection Row Validation
  COLLECTION_ROW_VALIDATION_FIELD_REQUIRED_ERROR: string;
  COLLECTION_ROW_VALIDATION_AT_LEAST_ONE_OPTION_ERROR: string;
  COLLECTION_ROW_VALIDATION_SELECT_DATE_PLACEHOLDER: string;
  COLLECTION_ROW_VALIDATION_SELECT_TYPE_PLACEHOLDER: string;
  COLLECTION_ROW_VALIDATION_SELECT_OPTION_PLACEHOLDER: string;
  COLLECTION_ROW_VALIDATION_NO_FIELDS_ADDED_MESSAGE: string;

  // COLLECTION_ROW_FILE - Collection Row File Upload
  COLLECTION_ROW_FILE_UPLOAD_INSTRUCTIONS: string;
  COLLECTION_ROW_FILE_UPLOAD_WAITING: string;
  COLLECTION_ROW_FILE_SUPPORTED_LABEL: string;
  COLLECTION_ROW_FILE_SIZE_LIMIT: string;

  // COLLECTION_ROW_MODAL - Collection Row Modals
  COLLECTION_ROW_MODAL_TRASH_TITLE: string;
  COLLECTION_ROW_MODAL_TRASH_DESCRIPTION: string;
  COLLECTION_ROW_MODAL_DELETE_TITLE: string;
  COLLECTION_ROW_MODAL_DELETE_DESCRIPTION: string;
  COLLECTION_ROW_MODAL_RESTORE_TITLE: string;
  COLLECTION_ROW_MODAL_RESTORE_DESCRIPTION: string;

  // COLLECTION_FIELD_SHEET - Collection Field Sheets
  COLLECTION_FIELD_SHEET_CREATE_TITLE: string;
  COLLECTION_FIELD_SHEET_CREATE_DESCRIPTION: string;
  COLLECTION_FIELD_SHEET_UPDATE_TITLE: string;
  COLLECTION_FIELD_SHEET_UPDATE_DESCRIPTION: string;
  COLLECTION_FIELD_SHEET_SHOW_TITLE: string;
  COLLECTION_FIELD_SHEET_SHOW_DESCRIPTION: string;
  COLLECTION_FIELD_SHEET_MANAGEMENT_TITLE: string;
  COLLECTION_FIELD_SHEET_MANAGEMENT_DESCRIPTION: string;

  // COLLECTION_FIELD_BUTTON - Collection Field Buttons
  COLLECTION_FIELD_BUTTON_CREATE_LABEL: string;

  // COLLECTION_FIELD_FORM - Collection Field Form
  COLLECTION_FIELD_FORM_NAME_LABEL: string;
  COLLECTION_FIELD_FORM_NAME_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_TYPE_LABEL: string;
  COLLECTION_FIELD_FORM_TYPE_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_FORMAT_LABEL: string;
  COLLECTION_FIELD_FORM_FORMAT_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_OPTIONS_LABEL: string;
  COLLECTION_FIELD_FORM_OPTIONS_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_REQUIRED_LABEL: string;
  COLLECTION_FIELD_FORM_REQUIRED_DESCRIPTION: string;
  COLLECTION_FIELD_FORM_MULTIPLE_LABEL: string;
  COLLECTION_FIELD_FORM_MULTIPLE_DESCRIPTION: string;
  COLLECTION_FIELD_FORM_SHOW_LIST_LABEL: string;
  COLLECTION_FIELD_FORM_SHOW_LIST_DESCRIPTION: string;
  COLLECTION_FIELD_FORM_SHOW_FILTER_LABEL: string;
  COLLECTION_FIELD_FORM_SHOW_FILTER_DESCRIPTION: string;
  COLLECTION_FIELD_FORM_TRASH_LABEL: string;
  COLLECTION_FIELD_FORM_TRASH_DESCRIPTION: string;
  COLLECTION_FIELD_FORM_CATEGORY_LABEL: string;
  COLLECTION_FIELD_FORM_DEFAULT_VALUE_LABEL: string;
  COLLECTION_FIELD_FORM_DEFAULT_VALUE_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_RELATIONSHIP_LIST_LABEL: string;
  COLLECTION_FIELD_FORM_RELATIONSHIP_LIST_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_RELATIONSHIP_FIELD_LABEL: string;
  COLLECTION_FIELD_FORM_RELATIONSHIP_FIELD_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_ORDER_LABEL: string;
  COLLECTION_FIELD_FORM_ORDER_PLACEHOLDER: string;
  COLLECTION_FIELD_FORM_GROUP_DROPDOWN_LABEL: string;

  // COLLECTION_FIELD_OPTIONS - Collection Field Options
  COLLECTION_FIELD_OPTIONS_YES: string;
  COLLECTION_FIELD_OPTIONS_NO: string;

  // COLLECTION_FIELD_VALIDATION - Collection Field Validation
  COLLECTION_FIELD_VALIDATION_NAME_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_TYPE_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_FORMAT_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_OPTIONS_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_CATEGORY_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_CATEGORY_EMPTY: string;
  COLLECTION_FIELD_VALIDATION_RELATIONSHIP_LIST_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_RELATIONSHIP_FIELD_REQUIRED: string;
  COLLECTION_FIELD_VALIDATION_ORDER_REQUIRED: string;

  // COLLECTION_FIELD_MANAGEMENT - Collection Field Management
  COLLECTION_FIELD_MANAGEMENT_EDIT_TOOLTIP: string;
  COLLECTION_FIELD_MANAGEMENT_DRAG_TOOLTIP: string;

  // FIELD_TYPE - Field Types
  FIELD_TYPE_TEXT_SHORT_LABEL: string;
  FIELD_TYPE_TEXT_LONG_LABEL: string;
  FIELD_TYPE_DROPDOWN_LABEL: string;
  FIELD_TYPE_FILE_LABEL: string;
  FIELD_TYPE_DATE_LABEL: string;
  FIELD_TYPE_RELATIONSHIP_LABEL: string;
  FIELD_TYPE_FIELD_GROUP_LABEL: string;
  FIELD_TYPE_CATEGORY_LABEL: string;
  FIELD_TYPE_REACTION_LABEL: string;
  FIELD_TYPE_EVALUATION_LABEL: string;

  // FIELD_FORMAT - Field Formats
  FIELD_FORMAT_ALPHANUMERIC_LABEL: string;
  FIELD_FORMAT_INTEGER_LABEL: string;
  FIELD_FORMAT_DECIMAL_LABEL: string;
  FIELD_FORMAT_URL_LABEL: string;
  FIELD_FORMAT_EMAIL_LABEL: string;

  // FIELD_ORDER - Field Order
  FIELD_ORDER_ASCENDING_LABEL: string;
  FIELD_ORDER_DESCENDING_LABEL: string;

  // PROFILE_ROUTE - Profile Route
  PROFILE_ROUTE_TITLE: string;
  PROFILE_ROUTE_ERROR_TITLE: string;
  PROFILE_ROUTE_ERROR_DESCRIPTION: string;

  // PROFILE_FORM - Profile Form Fields
  PROFILE_FORM_FIELD_NAME_LABEL: string;
  PROFILE_FORM_FIELD_NAME_PLACEHOLDER: string;
  PROFILE_FORM_FIELD_EMAIL_LABEL: string;
  PROFILE_FORM_FIELD_EMAIL_PLACEHOLDER: string;
  PROFILE_FORM_FIELD_ROLE_PLACEHOLDER: string;
  PROFILE_FORM_FIELD_CHANGE_PASSWORD_LABEL: string;
  PROFILE_FORM_FIELD_CHANGE_PASSWORD_DESCRIPTION: string;
  PROFILE_FORM_FIELD_CURRENT_PASSWORD_LABEL: string;
  PROFILE_FORM_FIELD_NEW_PASSWORD_LABEL: string;
  PROFILE_FORM_FIELD_CONFIRM_NEW_PASSWORD_LABEL: string;

  // PROFILE_VALIDATION - Profile Validation Messages
  PROFILE_VALIDATION_NEW_PASSWORD_DIFFERENT_ERROR: string;
  PROFILE_VALIDATION_PASSWORDS_MUST_MATCH_ERROR: string;

  // SYSTEM_ROUTE - System Settings Route
  SYSTEM_ROUTE_TITLE: string;
  SYSTEM_ROUTE_DESCRIPTION: string;

  // SYSTEM_LANGUAGE - System Language Settings
  SYSTEM_LANGUAGE_SETTINGS_TITLE: string;
  SYSTEM_LANGUAGE_SETTINGS_DESCRIPTION: string;
  SYSTEM_LANGUAGE_FIELD_DEFAULT_LABEL: string;
  SYSTEM_LANGUAGE_FIELD_DEFAULT_DESCRIPTION: string;
  SYSTEM_LANGUAGE_FIELD_DEFAULT_PLACEHOLDER: string;
  SYSTEM_LANGUAGE_OPTION_PT_BR: string;
  SYSTEM_LANGUAGE_OPTION_EN_US: string;

  // SYSTEM_FILE_UPLOAD - System File Upload Settings
  SYSTEM_FILE_UPLOAD_SETTINGS_TITLE: string;
  SYSTEM_FILE_UPLOAD_SETTINGS_DESCRIPTION: string;
  SYSTEM_FILE_UPLOAD_MAX_SIZE_LABEL: string;
  SYSTEM_FILE_UPLOAD_MAX_SIZE_DESCRIPTION: string;
  SYSTEM_FILE_UPLOAD_MAX_FILES_LABEL: string;
  SYSTEM_FILE_UPLOAD_MAX_FILES_DESCRIPTION: string;
  SYSTEM_FILE_UPLOAD_ACCEPTED_LABEL: string;
  SYSTEM_FILE_UPLOAD_ACCEPTED_DESCRIPTION: string;
  SYSTEM_FILE_UPLOAD_PATH_LABEL: string;
  SYSTEM_FILE_UPLOAD_PATH_DESCRIPTION: string;
  SYSTEM_FILE_UPLOAD_TEMP_PATH_LABEL: string;
  SYSTEM_FILE_UPLOAD_TEMP_PATH_DESCRIPTION: string;

  // SYSTEM_PAGINATION - System Pagination Settings
  SYSTEM_PAGINATION_SETTINGS_TITLE: string;
  SYSTEM_PAGINATION_SETTINGS_DESCRIPTION: string;
  SYSTEM_PAGINATION_PER_PAGE_LABEL: string;
  SYSTEM_PAGINATION_PER_PAGE_DESCRIPTION: string;

  // SYSTEM_BUTTON - System Buttons
  SYSTEM_BUTTON_UPDATE_LABEL: string;

  // SYSTEM_VALIDATION - System Validation Messages
  SYSTEM_VALIDATION_REQUIRED_FILE_MAX_SIZE: string;
  SYSTEM_VALIDATION_REQUIRED_FILE_ACCEPTED: string;
  SYSTEM_VALIDATION_REQUIRED_FILE_MAX_FILES: string;
  SYSTEM_VALIDATION_REQUIRED_FILE_PATH: string;
  SYSTEM_VALIDATION_REQUIRED_FILE_TEMP_PATH: string;
  SYSTEM_VALIDATION_REQUIRED_PAGINATION: string;

  // DASHBOARD - Dashboard Content
  DASHBOARD_TITLE: string;
  DASHBOARD_DATABASE_ACTIVITY_TITLE: string;
  DASHBOARD_TABLE_DISTRIBUTION_TITLE: string;
  DASHBOARD_BY_DATA_TYPE_SUBTITLE: string;
  DASHBOARD_DAY_MON: string;
  DASHBOARD_DAY_TUE: string;
  DASHBOARD_DAY_WED: string;
  DASHBOARD_DAY_THU: string;
  DASHBOARD_DAY_FRI: string;
  DASHBOARD_DAY_SAT: string;
  DASHBOARD_DAY_SUN: string;
  DASHBOARD_CATEGORY_PRODUCTS: string;
  DASHBOARD_CATEGORY_USERS: string;
  DASHBOARD_CATEGORY_SALES: string;
  DASHBOARD_CATEGORY_REPORTS: string;

  // TREE_EDITOR - Tree Editor Component
  TREE_EDITOR_ADD_NODE_PLACEHOLDER: string;
  TREE_EDITOR_SAVE_BUTTON: string;
  TREE_EDITOR_CANCEL_BUTTON: string;
  TREE_EDITOR_ADD_BUTTON: string;
  TREE_EDITOR_NO_ITEM_SELECTED: string;
  TREE_EDITOR_CLICK_ADD_TO_START: string;

  // UPLOADER - File Upload Component
  UPLOADER_DRAG_DROP_INSTRUCTION: string;
  UPLOADER_CLICK_TO_UPLOAD: string;
  UPLOADER_UPLOADING_WAIT: string;
  UPLOADER_SUPPORTED_FILES: string;
  UPLOADER_FILE_SIZE_LIMIT: string;

  // THEME - Theme Toggle
  THEME_TOGGLE_TOOLTIP: string;

  // COLLECTION_TRASH - Collection Trash Features
  COLLECTION_TRASH_VIEW_TRASH: string;
  COLLECTION_TRASH_EXIT_TRASH: string;

  // FIELD_MANAGEMENT - Field Management
  FIELD_MANAGEMENT_UPDATE_ORDER: string;
  FIELD_MANAGEMENT_FORM_ORDER: string;
  FIELD_MANAGEMENT_TRASH_LABEL: string;

  // DATE_FORMATS - Date Format Labels
  DATE_FORMAT_DD_MM_YYYY: string;
  DATE_FORMAT_MM_DD_YYYY: string;
  DATE_FORMAT_YYYY_MM_DD: string;
  DATE_FORMAT_DD_MM_YYYY_TIME: string;
  DATE_FORMAT_MM_DD_YYYY_TIME: string;
  DATE_FORMAT_YYYY_MM_DD_TIME: string;
  DATE_FORMAT_DD_MM_YYYY_DASH: string;
  DATE_FORMAT_MM_DD_YYYY_DASH: string;
  DATE_FORMAT_YYYY_MM_DD_DASH: string;
  DATE_FORMAT_DD_MM_YYYY_TIME_DASH: string;
  DATE_FORMAT_MM_DD_YYYY_TIME_DASH: string;
  DATE_FORMAT_YYYY_MM_DD_TIME_DASH: string;

  // PLACEHOLDERS - Common Placeholders
  PLACEHOLDER_FILE_SIZE_10MB: string;
  PLACEHOLDER_MAX_FILES_5: string;
  PLACEHOLDER_FILE_TYPES: string;
  PLACEHOLDER_STORAGE_PATH: string;
  PLACEHOLDER_PAGINATION_50: string;

  // VALIDATION_GENERIC - Generic Validation Messages
  VALIDATION_NAME_REQUIRED: string;
  VALIDATION_EMAIL_REQUIRED: string;
  VALIDATION_PASSWORD_REQUIRED: string;
  VALIDATION_GROUP_REQUIRED: string;
  VALIDATION_EMAIL_ALREADY_EXISTS: string;
  VALIDATION_FIELD_REQUIRED: string;
  VALIDATION_AT_LEAST_ONE_OPTION: string;
  VALIDATION_UNPROCESSABLE_ENTITY: string;

  // TOAST_MESSAGES - Toast Success Messages
  TOAST_USER_ADDED: string;
  TOAST_USER_ADDED_DESCRIPTION: string;
  TOAST_COLLECTION_CREATED: string;
  TOAST_COLLECTION_CREATED_DESCRIPTION: string;
  TOAST_ITEM_RESTORED: string;
  TOAST_ITEM_DELETED: string;
  TOAST_OPERATION_SUCCESS: string;

  // ERROR_SPECIFIC - Specific Error Messages
  ERROR_OWNER_REQUIRED: string;
  ERROR_GROUP_NOT_INFORMED: string;
  ERROR_GROUP_NOT_FOUND: string;
  ERROR_USER_ALREADY_EXISTS: string;
  ERROR_COLLECTION_NAME_EXISTS: string;
  ERROR_INVALID_CREDENTIALS: string;
  ERROR_USER_INACTIVE: string;
  ERROR_FIELD_NOT_FOUND: string;
  ERROR_PERMISSION_DENIED: string;
  ERROR_VALIDATION_FAILED: string;

  // MODAL_GENERIC - Generic Modal Content
  MODAL_CONFIRMATION_TITLE: string;
  MODAL_CONFIRMATION_DESCRIPTION: string;
  MODAL_DELETE_CONFIRMATION: string;
  MODAL_RESTORE_CONFIRMATION: string;
  MODAL_TRASH_CONFIRMATION: string;
  MODAL_CANCEL_BUTTON: string;
  MODAL_CONFIRM_BUTTON: string;

  // STATUS_LABELS - Status and Badge Labels
  STATUS_ACTIVE: string;
  STATUS_INACTIVE: string;
  STATUS_PENDING: string;
  STATUS_COMPLETED: string;
  STATUS_PUBLIC: string;
  STATUS_RESTRICTED: string;
  STATUS_OPEN: string;
  STATUS_CLOSED: string;

  // COLLECTION_FEATURES - Collection Specific Features
  COLLECTION_TYPE_COLLECTION: string;
  COLLECTION_TYPE_FIELD_GROUP: string;
  COLLECTION_STYLE_LIST: string;
  COLLECTION_STYLE_GRID: string;
  COLLECTION_STYLE_GALLERY: string;
  COLLECTION_VISIBILITY_PUBLIC: string;
  COLLECTION_VISIBILITY_RESTRICTED: string;
  COLLECTION_COLLABORATION_OPEN: string;
  COLLECTION_COLLABORATION_RESTRICTED: string;

  // EMPTY_STATES - Empty State Messages
  EMPTY_STATE_NO_DATA: string;
  EMPTY_STATE_NO_FIELDS: string;
  EMPTY_STATE_NO_RECORDS: string;
  EMPTY_STATE_NO_RESULTS: string;
  EMPTY_STATE_NO_COLLECTIONS: string;
  EMPTY_STATE_NO_USERS: string;
  EMPTY_STATE_NO_GROUPS: string;

  // LOADING_STATES - Loading Messages
  LOADING_DATA: string;
  LOADING_PLEASE_WAIT: string;
  LOADING_UPLOADING: string;
  LOADING_PROCESSING: string;
  LOADING_SAVING: string;

  // TIME_LABELS - Time Related Labels
  TIME_CREATED_AT: string;
  TIME_UPDATED_AT: string;
  TIME_DELETED_AT: string;
  TIME_LAST_LOGIN: string;
  TIME_LAST_MODIFIED: string;

  // SORT_LABELS - Sorting Labels
  SORT_NAME_ASC: string;
  SORT_NAME_DESC: string;
  SORT_DATE_ASC: string;
  SORT_DATE_DESC: string;
  SORT_ALPHABETICAL: string;
  SORT_REVERSE_ALPHABETICAL: string;

  // PROFILE - Profile Page
  PROFILE_PAGE_TITLE: string;
  PROFILE_PAGE_DESCRIPTION: string;
  PROFILE_ERROR_TITLE: string;
  PROFILE_ERROR_DESCRIPTION: string;
  PROFILE_DROPDOWN_USER_AVATAR_ALT: string;
  PROFILE_DROPDOWN_PROFILE_MENU_ITEM: string;
  PROFILE_DROPDOWN_LOGOUT_MENU_ITEM: string;

  // DASHBOARD - Dashboard Page
  DASHBOARD_PAGE_TITLE: string;
  DASHBOARD_PAGE_DESCRIPTION: string;

  // SYSTEM_ROUTE_EXTENDED - Extended System Settings Route
  SYSTEM_ROUTE_LANGUAGE_SETTINGS_TITLE: string;
  SYSTEM_ROUTE_LANGUAGE_SETTINGS_DESCRIPTION: string;
  SYSTEM_ROUTE_FILE_UPLOAD_SETTINGS_TITLE: string;
  SYSTEM_ROUTE_FILE_UPLOAD_SETTINGS_DESCRIPTION: string;
  SYSTEM_ROUTE_PAGINATION_SETTINGS_TITLE: string;
  SYSTEM_ROUTE_PAGINATION_SETTINGS_DESCRIPTION: string;
  SYSTEM_ROUTE_BUTTON_UPDATE_LABEL: string;
  SYSTEM_ROUTE_FILE_UPLOAD_MAX_SIZE_LABEL: string;
  SYSTEM_ROUTE_FILE_UPLOAD_MAX_SIZE_DESCRIPTION: string;
  SYSTEM_ROUTE_FILE_UPLOAD_MAX_FILES_LABEL: string;
  SYSTEM_ROUTE_FILE_UPLOAD_MAX_FILES_DESCRIPTION: string;
  SYSTEM_ROUTE_FILE_UPLOAD_ACCEPTED_LABEL: string;
  SYSTEM_ROUTE_FILE_UPLOAD_ACCEPTED_DESCRIPTION: string;
  SYSTEM_ROUTE_FILE_UPLOAD_PATH_LABEL: string;
  SYSTEM_ROUTE_FILE_UPLOAD_PATH_DESCRIPTION: string;
  SYSTEM_ROUTE_PAGINATION_PER_PAGE_LABEL: string;
  SYSTEM_ROUTE_PAGINATION_PER_PAGE_DESCRIPTION: string;
  SYSTEM_ROUTE_SHEET_FIELD_DEFAULT_LANGUAGE_LABEL: string;
  SYSTEM_ROUTE_SHEET_FIELD_DEFAULT_LANGUAGE_DESCRIPTION: string;
  SYSTEM_ROUTE_SHEET_FIELD_DEFAULT_LANGUAGE_PLACEHOLDER: string;
  SYSTEM_ROUTE_SHEET_FIELD_DEFAULT_LANGUAGE_OPTION_PT_BR: string;
  SYSTEM_ROUTE_SHEET_FIELD_DEFAULT_LANGUAGE_OPTION_EN_US: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_FILE_MAX_SIZE: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_FILE_ACCEPTED: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_FILE_MAX_FILES: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_FILE_PATH: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_PAGINATION: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_BASE_URL: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_DATABASE_URL: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_DATABASE_NAME: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_EMAIL_HOST: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_EMAIL_PORT: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_EMAIL_USER: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_EMAIL_PASSWORD: string;
  SYSTEM_ROUTE_FORM_VALIDATION_REQUIRED_EMAIL_FROM: string;

  // SYSTEM_GENERAL - System General Settings
  SYSTEM_ROUTE_GENERAL_SETTINGS_TITLE: string;
  SYSTEM_ROUTE_GENERAL_SETTINGS_DESCRIPTION: string;
  SYSTEM_ROUTE_BASE_URL_LABEL: string;
  SYSTEM_ROUTE_BASE_URL_DESCRIPTION: string;

  // SYSTEM_DATABASE - System Database Settings
  SYSTEM_ROUTE_DATABASE_SETTINGS_TITLE: string;
  SYSTEM_ROUTE_DATABASE_SETTINGS_DESCRIPTION: string;
  SYSTEM_ROUTE_DATABASE_URL_LABEL: string;
  SYSTEM_ROUTE_DATABASE_URL_DESCRIPTION: string;
  SYSTEM_ROUTE_DATABASE_NAME_LABEL: string;
  SYSTEM_ROUTE_DATABASE_NAME_DESCRIPTION: string;

  // SYSTEM_EMAIL - System Email Settings
  SYSTEM_ROUTE_EMAIL_SETTINGS_TITLE: string;
  SYSTEM_ROUTE_EMAIL_SETTINGS_DESCRIPTION: string;
  SYSTEM_ROUTE_EMAIL_HOST_LABEL: string;
  SYSTEM_ROUTE_EMAIL_HOST_DESCRIPTION: string;
  SYSTEM_ROUTE_EMAIL_PORT_LABEL: string;
  SYSTEM_ROUTE_EMAIL_PORT_DESCRIPTION: string;
  SYSTEM_ROUTE_EMAIL_USER_LABEL: string;
  SYSTEM_ROUTE_EMAIL_USER_DESCRIPTION: string;
  SYSTEM_ROUTE_EMAIL_PASSWORD_LABEL: string;
  SYSTEM_ROUTE_EMAIL_PASSWORD_DESCRIPTION: string;
  SYSTEM_ROUTE_EMAIL_FROM_LABEL: string;
  SYSTEM_ROUTE_EMAIL_FROM_DESCRIPTION: string;

  // USER_ROUTE_SHEET - User Form Sheets
  USER_ROUTE_SHEET_CREATE_TITLE: string;
  USER_ROUTE_SHEET_CREATE_DESCRIPTION: string;
  USER_ROUTE_SHEET_UPDATE_TITLE: string;
  USER_ROUTE_SHEET_UPDATE_DESCRIPTION: string;
  USER_ROUTE_SHEET_SHOW_TITLE: string;
  USER_ROUTE_SHEET_SHOW_DESCRIPTION: string;
  USER_ROUTE_SHEET_FIELD_NAME_LABEL: string;
  USER_ROUTE_SHEET_FIELD_NAME_PLACEHOLDER: string;
  USER_ROUTE_SHEET_FIELD_EMAIL_LABEL: string;
  USER_ROUTE_SHEET_FIELD_EMAIL_PLACEHOLDER: string;
  USER_ROUTE_SHEET_FIELD_PASSWORD_LABEL: string;
  USER_ROUTE_SHEET_FIELD_PASSWORD_PLACEHOLDER: string;
  USER_ROUTE_SHEET_FIELD_GROUP_LABEL: string;
  USER_ROUTE_SHEET_FIELD_GROUP_PLACEHOLDER: string;
  USER_ROUTE_SHEET_FIELD_STATUS_LABEL: string;
  USER_ROUTE_SHEET_FIELD_STATUS_DESCRIPTION: string;
  USER_ROUTE_SHEET_FIELD_STATUS_ACTIVE_OPTION: string;
  USER_ROUTE_SHEET_FIELD_STATUS_INACTIVE_OPTION: string;

  // COLLECTION_ROUTE_SHEET - Collection Form Sheets
  COLLECTION_ROUTE_SHEET_CREATE_TITLE: string;
  COLLECTION_ROUTE_SHEET_CREATE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_UPDATE_TITLE: string;
  COLLECTION_ROUTE_SHEET_UPDATE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_SHOW_TITLE: string;
  COLLECTION_ROUTE_SHEET_SHOW_DESCRIPTION: string;
  COLLECTION_SHEET_FIELD_NAME_LABEL: string;
  COLLECTION_SHEET_FIELD_NAME_PLACEHOLDER: string;
  COLLECTION_SHEET_FIELD_DESCRIPTION_LABEL: string;
  COLLECTION_SHEET_FIELD_DESCRIPTION_PLACEHOLDER: string;

  // USER_GROUP_ROUTE_SHEET - User Group Form Sheets
  USER_GROUP_ROUTE_SHEET_CREATE_TITLE: string;
  USER_GROUP_ROUTE_SHEET_CREATE_DESCRIPTION: string;
  USER_GROUP_ROUTE_SHEET_UPDATE_TITLE: string;
  USER_GROUP_ROUTE_SHEET_UPDATE_DESCRIPTION: string;
  USER_GROUP_ROUTE_SHEET_SHOW_TITLE: string;
  USER_GROUP_ROUTE_SHEET_SHOW_DESCRIPTION: string;

  // COLLECTION_ROW_ROUTE_SHEET - Collection Row Form Sheets
  COLLECTION_ROW_ROUTE_SHEET_CREATE_TITLE: string;
  COLLECTION_ROW_ROUTE_SHEET_CREATE_DESCRIPTION: string;
  COLLECTION_ROW_ROUTE_SHEET_UPDATE_TITLE: string;
  COLLECTION_ROW_ROUTE_SHEET_UPDATE_DESCRIPTION: string;
  COLLECTION_ROW_ROUTE_SHEET_SHOW_TITLE: string;
  COLLECTION_ROW_ROUTE_SHEET_SHOW_DESCRIPTION: string;

  // COLLECTION_FIELD_ROUTE_SHEET - Collection Field Form Sheets
  COLLECTION_FIELD_ROUTE_SHEET_CREATE_TITLE: string;
  COLLECTION_FIELD_ROUTE_SHEET_CREATE_DESCRIPTION: string;
  COLLECTION_FIELD_ROUTE_SHEET_UPDATE_TITLE: string;
  COLLECTION_FIELD_ROUTE_SHEET_UPDATE_DESCRIPTION: string;
  COLLECTION_FIELD_ROUTE_SHEET_SHOW_TITLE: string;
  COLLECTION_FIELD_ROUTE_SHEET_SHOW_DESCRIPTION: string;
  COLLECTION_FIELD_ROUTE_SHEET_MANAGEMENT_TITLE: string;
  COLLECTION_FIELD_ROUTE_SHEET_MANAGEMENT_DESCRIPTION: string;

  // BUTTON_LABELS - Common Button Labels
  BUTTON_CREATE_LABEL: string;
  BUTTON_UPDATE_LABEL: string;
  BUTTON_SAVE_LABEL: string;
  BUTTON_CANCEL_LABEL: string;
  BUTTON_DELETE_LABEL: string;
  BUTTON_EDIT_LABEL: string;
  BUTTON_ADD_LABEL: string;
  BUTTON_REMOVE_LABEL: string;
  BUTTON_CONFIRM_LABEL: string;
  BUTTON_CLOSE_LABEL: string;

  // TOAST_MESSAGES_EXTENDED - Additional Toast Messages
  TOAST_USER_CREATED: string;
  TOAST_USER_CREATED_DESCRIPTION: string;
  TOAST_USER_UPDATED: string;
  TOAST_USER_UPDATED_DESCRIPTION: string;
  TOAST_USER_DELETED: string;
  TOAST_USER_DELETED_DESCRIPTION: string;
  TOAST_COLLECTION_UPDATED: string;
  TOAST_COLLECTION_UPDATED_DESCRIPTION: string;
  TOAST_COLLECTION_DELETED: string;
  TOAST_COLLECTION_DELETED_DESCRIPTION: string;
  TOAST_RECORD_CREATED: string;
  TOAST_RECORD_CREATED_DESCRIPTION: string;
  TOAST_RECORD_UPDATED: string;
  TOAST_RECORD_UPDATED_DESCRIPTION: string;
  TOAST_RECORD_DELETED: string;
  TOAST_RECORD_DELETED_DESCRIPTION: string;
  TOAST_FIELD_CREATED: string;
  TOAST_FIELD_CREATED_DESCRIPTION: string;
  TOAST_FIELD_UPDATED: string;
  TOAST_FIELD_UPDATED_DESCRIPTION: string;
  TOAST_FIELD_DELETED: string;
  TOAST_FIELD_DELETED_DESCRIPTION: string;
  TOAST_SETTINGS_UPDATED: string;
  TOAST_SETTINGS_UPDATED_DESCRIPTION: string;

  // ERROR_MESSAGES_EXTENDED - Additional Error Messages
  ERROR_INVALID_DATA: string;
  ERROR_AUTHENTICATION_REQUIRED: string;
  ERROR_ACCESS_DENIED: string;
  ERROR_SERVER_ERROR: string;
  ERROR_RATE_LIMIT: string;
  ERROR_EMAIL_EXISTS: string;
  ERROR_NAME_EXISTS: string;
  ERROR_COLLECTION_NOT_FOUND: string;
  ERROR_RECORD_NOT_FOUND: string;

  // MODAL_CONFIRMATION_EXTENDED - Additional Modal Confirmations
  MODAL_DELETE_USER_TITLE: string;
  MODAL_DELETE_USER_DESCRIPTION: string;
  MODAL_DELETE_COLLECTION_TITLE: string;
  MODAL_DELETE_COLLECTION_DESCRIPTION: string;
  MODAL_DELETE_RECORD_TITLE: string;
  MODAL_DELETE_RECORD_DESCRIPTION: string;
  MODAL_DELETE_FIELD_TITLE: string;
  MODAL_DELETE_FIELD_DESCRIPTION: string;
  MODAL_SEND_TO_TRASH_TITLE: string;
  MODAL_SEND_TO_TRASH_DESCRIPTION: string;
  MODAL_RESTORE_FROM_TRASH_TITLE: string;
  MODAL_RESTORE_FROM_TRASH_DESCRIPTION: string;

  // VALIDATION_MESSAGES_EXTENDED - Additional Validation Messages
  VALIDATION_EMAIL_INVALID: string;
  VALIDATION_DESCRIPTION_REQUIRED: string;
  VALIDATION_TYPE_REQUIRED: string;
  VALIDATION_FORMAT_REQUIRED: string;
  VALIDATION_OPTIONS_REQUIRED: string;
  VALIDATION_PERMISSIONS_REQUIRED: string;
  VALIDATION_MIN_LENGTH: string;
  VALIDATION_MAX_LENGTH: string;
  VALIDATION_INVALID_FORMAT: string;

  // DASHBOARD_HARDCODED - Dashboard Content
  DASHBOARD_DATABASE_COUNT_TITLE: string;
  DASHBOARD_TABLES_COUNT_TITLE: string;
  DASHBOARD_ACTIVE_USERS_TITLE: string;
  DASHBOARD_GROWTH_FROM_LAST_MONTH: string;
  DASHBOARD_DATABASE_ACTIVITY_DESCRIPTION: string;
  DASHBOARD_TABLE_DISTRIBUTION_DESCRIPTION: string;

  // COLLECTION_ROW_RESTORE_MODAL - Collection Row Restore Modals
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_RESTORE_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_RESTORE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_CANCEL_BUTTON: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_CONFIRM_BUTTON: string;

  // TOAST_MESSAGES_ROW - Row Toast Messages
  TOAST_ROW_RESTORED: string;
  TOAST_ROW_RESTORED_DESCRIPTION: string;

  // ERROR_MESSAGES_ROW - Row Error Messages
  ERROR_INVALID_RECORD_ID: string;
  ERROR_RECORD_NOT_FOUND_IN_TRASH: string;

  // AUTHENTICATION_ERRORS - Authentication Error Messages
  ERROR_INVALID_CREDENTIALS_MESSAGE: string;
  ERROR_USER_INACTIVE_MESSAGE: string;
  ERROR_RATE_LIMIT_MESSAGE: string;
  ERROR_INTERNAL_SERVER_MESSAGE: string;
  ERROR_INVALID_DATA_MESSAGE: string;

  // ROOT_META - Root Page Meta
  ROOT_META_DESCRIPTION: string;
  ROOT_META_TITLE: string;

  // AUTHENTICATION_PLACEHOLDERS - Authentication Placeholders
  AUTH_SIGNIN_HELLO_MESSAGE: string;
  AUTH_RECOVERY_HELLO_MESSAGE: string;
  PROFILE_HELLO_MESSAGE: string;

  // PAGINATION_LABELS - Pagination Labels
  PAGINATION_PER_PAGE_LABEL: string;
  PAGINATION_PAGE_LABEL: string;

  // ACTION_LABELS - Action Labels
  ACTION_LABEL: string;
  ACTION_SHOW_LABEL: string;
  ACTION_UPDATE_LABEL: string;

  // USER_GROUP_ROUTE_SHEET_FIELDS - User Group Form Fields
  USER_GROUP_ROUTE_SHEET_FIELD_NAME_LABEL: string;
  USER_GROUP_ROUTE_SHEET_FIELD_NAME_PLACEHOLDER: string;
  USER_GROUP_ROUTE_SHEET_FIELD_DESCRIPTION_LABEL: string;
  USER_GROUP_ROUTE_SHEET_FIELD_DESCRIPTION_PLACEHOLDER: string;
  USER_GROUP_ROUTE_SHEET_FIELD_PERMISSIONS_LABEL: string;

  // USER_ROUTE_SHEET_FIELDS - User Form Fields
  USER_ROUTE_SHEET_FIELD_ROLE_LABEL: string;
  USER_ROUTE_SHEET_FIELD_ROLE_PLACEHOLDER: string;

  // COLLECTION_FORM_EXTENDED - Extended Collection Form Fields
  COLLECTION_SHEET_FIELD_COLLABORATOR_OPEN_OPTION: string;
  COLLECTION_SELECT_PLACEHOLDER: string;

  // MISSING_KEYS - Additional Missing Keys
  ACTION_RESTORE_LABEL: string;
  ACTION_DELETE_LABEL: string;
  COLLECTION_SHEET_FIELD_ADMINISTRATOR_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_DELETE_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_DELETE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_FILTER_TITLE: string;
  COLLECTION_ROUTE_SHEET_FILTER_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_TRASH_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_MODAL_TRASH_DESCRIPTION: string;
  COLLECTION_SHEET_FIELD_LOGO_LABEL: string;
  COLLECTION_SHEET_FIELD_LOGO_PLACEHOLDER: string;
  COLLECTION_SHEET_FIELD_LAYOUT_LABEL: string;
  COLLECTION_SHEET_FIELD_LAYOUT_DESCRIPTION: string;
  COLLECTION_SHEET_FIELD_VISIBILITY_LABEL: string;
  COLLECTION_SHEET_FIELD_VISIBILITY_PUBLIC_OPTION: string;
  COLLECTION_SHEET_FIELD_VISIBILITY_RESTRICTED_OPTION: string;
  COLLECTION_SHEET_FIELD_COLLABORATOR_LABEL: string;
  COLLECTION_SHEET_FIELD_COLLABORATOR_RESTRICTED_OPTION: string;

  // NEW_MISSING_KEYS - Recently Found Missing Translation Keys
  INPUT_SEARCH_PLACEHOLDER: string;
  NAVIGATION_LOADING_PERMISSIONS: string;
  BUTTON_CLEAR_LABEL: string;
  BUTTON_SEARCH_LABEL: string;
  ACTION_INTERNAL_LABEL: string;
  ACTION_SHARE_LABEL: string;
  FIELD_TYPE_TREE_LABEL: string;
  FIELD_TYPE_LIKE_LABEL: string;
  FIELD_TYPE_RATING_LABEL: string;
  COLLECTION_INTERNAL_CONFIGURATION_DROPDOWN_LABEL: string;
  COLLECTION_INTERNAL_CONFIGURATION_DROPDOWN_OPTION_MANAGER_FIELD: string;
  COLLECTION_INTERNAL_FIELD_BUTTON_CREATE_LABEL: string;
  COLLECTION_INTERNAL_REGISTER_BUTTON_CREATE_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FILTER_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FILTER_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_CREATE_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_CREATE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_UPDATE_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_UPDATE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_NAME_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_NAME_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_NAME_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TYPE_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TYPE_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TYPE_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_FORMAT_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_FORMAT_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_FORMAT_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_REQUIRED_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_REQUIRED_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_MULTIPLE_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_MULTIPLE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_SHOW_LIST_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_SHOW_LIST_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_SHOW_FILTER_LABEL: string;

  // COLLECTION_HARDCODED - Collection Hardcoded Strings
  COLLECTION_ERROR_INVALID_DATA: string;
  COLLECTION_ERROR_OWNER_REQUIRED: string;
  COLLECTION_ERROR_AUTHENTICATION_REQUIRED: string;
  COLLECTION_ERROR_ACCESS_DENIED: string;
  COLLECTION_ERROR_ALREADY_EXISTS: string;
  COLLECTION_ERROR_VALIDATION: string;
  COLLECTION_ERROR_INTERNAL_SERVER: string;
  COLLECTION_ERROR_INVALID_ID: string;
  COLLECTION_ERROR_NOT_FOUND: string;
  COLLECTION_ERROR_NOT_FOUND_TRASH: string;
  COLLECTION_ERROR_INSUFFICIENT_PERMISSIONS: string;
  COLLECTION_ERROR_CANNOT_RESTORE: string;
  COLLECTION_TOAST_CREATED: string;
  COLLECTION_TOAST_CREATED_DESCRIPTION: string;
  COLLECTION_TOAST_RESTORED: string;
  COLLECTION_TOAST_RESTORED_DESCRIPTION: string;
  COLLECTION_TOAST_LINK_COPIED: string;
  COLLECTION_TOAST_LINK_COPIED_DESCRIPTION: string;
  COLLECTION_SORT_ASCENDING: string;
  COLLECTION_SORT_DESCENDING: string;
  COLLECTION_DIALOG_RESTORE_TITLE: string;
  COLLECTION_DIALOG_RESTORE_DESCRIPTION: string;
  COLLECTION_DIALOG_CANCEL_BUTTON: string;
  COLLECTION_DIALOG_CONFIRM_BUTTON: string;

  // COLLECTION_ADDITIONAL - Additional Collection Strings
  COLLECTION_TRASH_VIEW_LABEL: string;
  COLLECTION_TRASH_EXIT_LABEL: string;
  COLLECTION_FIELD_MANAGER_ORDER_UPDATE_BUTTON: string;
  COLLECTION_FIELD_MANAGER_ORDER_LIST_TITLE: string;
  COLLECTION_FIELD_MANAGER_ORDER_FORM_TITLE: string;
  COLLECTION_FIELD_LISTING_LABEL: string;
  COLLECTION_FIELD_LISTING_DESCRIPTION: string;
  COLLECTION_SELECT_TYPE_PLACEHOLDER: string;
  COLLECTION_SELECT_DATE_PLACEHOLDER: string;
  COLLECTION_SELECT_OPTION_PLACEHOLDER: string;
  COLLECTION_SELECT_COLUMN_PLACEHOLDER: string;
  COLLECTION_SELECT_ORDER_PLACEHOLDER: string;
  COLLECTION_SELECT_FORMAT_PLACEHOLDER: string;
  COLLECTION_SELECT_LIST_RELATIONSHIP_PLACEHOLDER: string;
  COLLECTION_SELECT_ADMINISTRATORS_PLACEHOLDER: string;
  COLLECTION_SELECT_LAYOUT_PLACEHOLDER: string;
  COLLECTION_SELECT_GENERIC_PLACEHOLDER: string;
  COLLECTION_FORM_EXTERNAL_VALUE_SYNC_COMMENT: string;

  // SETTINGS - System Settings
  SETTINGS_ERROR_INVALID_DATA: string;
  SETTINGS_ERROR_AUTHENTICATION_REQUIRED: string;
  SETTINGS_ERROR_VALIDATION: string;
  SETTINGS_LANGUAGE_DEFAULT_LABEL: string;
  SETTINGS_LANGUAGE_DEFAULT_DESCRIPTION: string;
  SETTINGS_LANGUAGE_PORTUGUESE_BRAZIL: string;
  SETTINGS_FILE_MAX_SIZE_LABEL: string;
  SETTINGS_FILE_MAX_UPLOADS_LABEL: string;
  SETTINGS_FILE_MAX_UPLOADS_DESCRIPTION: string;
  SETTINGS_FILE_EXTENSIONS_DESCRIPTION: string;
  SETTINGS_STORAGE_DIRECTORY_LABEL: string;
  SETTINGS_STORAGE_DIRECTORY_DESCRIPTION: string;
  SETTINGS_PAGINATION_ITEMS_LABEL: string;
  SETTINGS_PAGINATION_ITEMS_DESCRIPTION: string;

  // USER - User Management (Additional)
  USER_ERROR_INVALID_DATA: string;
  USER_ERROR_AUTHENTICATION_REQUIRED: string;
  USER_ERROR_NOT_FOUND: string;
  USER_ERROR_GROUP_NOT_FOUND: string;
  USER_ERROR_EMAIL_ALREADY_EXISTS: string;
  USER_FORM_STATUS_DESCRIPTION: string;
  USER_FORM_UPDATE_DESCRIPTION: string;
  USER_FORM_CREATE_DESCRIPTION: string;
  USER_TOAST_UPDATED: string;
  USER_TOAST_UPDATED_DESCRIPTION: string;

  // USER_GROUP - User Group Management (Additional)
  USER_GROUP_ERROR_INVALID_DATA: string;
  USER_GROUP_ERROR_AUTHENTICATION_REQUIRED: string;
  USER_GROUP_ERROR_NOT_FOUND: string;
  USER_GROUP_ERROR_PERMISSIONS_NOT_FOUND: string;
  USER_GROUP_ERROR_NAME_ALREADY_EXISTS: string;
  USER_GROUP_ERROR_CANNOT_MODIFY_HAS_USERS: string;
  USER_GROUP_FORM_DESCRIPTION_LABEL: string;
  USER_GROUP_FORM_DESCRIPTION_PLACEHOLDER: string;
  USER_GROUP_FORM_CREATE_DESCRIPTION: string;
  USER_GROUP_FORM_UPDATE_DESCRIPTION: string;
  USER_GROUP_SELECT_PERMISSIONS_PLACEHOLDER: string;
  USER_GROUP_TOAST_CREATED: string;
  USER_GROUP_TOAST_UPDATED: string;
  USER_GROUP_TOAST_UPDATED_DESCRIPTION: string;

  // COLLECTION_ADDITIONAL - Additional Collection Strings
  COLLECTION_FIELD_GROUP_LABEL: string;
  COLLECTION_ROW_RESTORE_DESCRIPTION: string;
  COLLECTION_FIELD_SENT_TO_TRASH_MESSAGE: string;
  COLLECTION_FIELD_RESTORED_MESSAGE: string;
  COLLECTION_FIELD_ERROR_INSUFFICIENT_PERMISSIONS: string;
  COLLECTION_FIELD_ERROR_NOT_FOUND: string;
  COLLECTION_FIELD_ERROR_NAME_ALREADY_EXISTS: string;
  COLLECTION_FIELD_ERROR_CANNOT_CHANGE_TYPE: string;
  COLLECTION_FIELD_ERROR_INVALID_CONFIGURATION: string;
  COLLECTION_ROW_ERROR_INVALID_ID: string;
  COLLECTION_ROW_ERROR_NOT_FOUND: string;
  COLLECTION_ROW_ERROR_CANNOT_DELETE_REFERENCED: string;
  COLLECTION_ROW_DELETE_DESCRIPTION: string;
  COLLECTION_FIELD_REQUIRED_SUFFIX: string;
  COLLECTION_DROPDOWN_VALIDATION_ADD_OPTION: string;
  COLLECTION_FILE_ERROR_INVALID_DATA: string;
  COLLECTION_FILE_ERROR_TYPE_NOT_ALLOWED: string;
  COLLECTION_FILE_ERROR_VIRUS_CHECK_FAILED: string;
  COLLECTION_FILE_ERROR_INVALID_ID: string;
  COLLECTION_FILE_ERROR_NOT_FOUND: string;
  COLLECTION_FILE_ERROR_CANNOT_DELETE_IN_USE: string;

  // FIELD_TYPE_LABELS - Field Type Labels (Additional)
  FIELD_TYPE_TREE_ADDITIONAL_LABEL: string;
  FIELD_TYPE_RATING_ADDITIONAL_LABEL: string;
  FIELD_FORMAT_ALPHANUMERIC_ADDITIONAL_LABEL: string;

  // COLLECTION_TRASH_OPERATIONS - Trash Operations
  COLLECTION_TRASH_SEND_ROW_TITLE: string;
  COLLECTION_TRASH_SEND_ROW_DESCRIPTION: string;
  COLLECTION_TRASH_SEND_COLLECTION_TITLE: string;
  COLLECTION_TRASH_SEND_COLLECTION_DESCRIPTION: string;
  COLLECTION_TRASH_RESTORE_ROW_TITLE: string;
  COLLECTION_TRASH_CANNOT_MOVE_HAS_DATA: string;
  COLLECTION_TOAST_ROW_SENT_TO_TRASH: string;
  COLLECTION_TOAST_ROW_SENT_TO_TRASH_DESCRIPTION: string;
  COLLECTION_TOAST_COLLECTION_SENT_TO_TRASH: string;
  COLLECTION_TOAST_COLLECTION_SENT_TO_TRASH_DESCRIPTION: string;

  // COLLECTION_FIELD_CONFIG - Field Configuration Labels
  COLLECTION_FIELD_ALLOCATE_TO_TRASH: string;
  COLLECTION_FIELD_ALLOCATE_TO_TRASH_DESCRIPTION: string;
  COLLECTION_FIELD_REQUIRED_LABEL: string;
  COLLECTION_FIELD_REQUIRED_DESCRIPTION: string;
  COLLECTION_FIELD_TREE_STRUCTURE_LABEL: string;
  COLLECTION_FIELD_DEFAULT_LABEL: string;
  COLLECTION_FIELD_COLUMN_DISPLAYED_REQUIRED: string;
  COLLECTION_FIELD_NAME_REQUIRED: string;
  COLLECTION_FIELD_ORDER_REQUIRED: string;
  COLLECTION_FIELD_FORMAT_REQUIRED: string;

  // COLLECTION_VALIDATION_MESSAGES - Field Validation Messages
  COLLECTION_VALIDATION_FIELD_REQUIRED: string;
  COLLECTION_VALIDATION_ADD_AT_LEAST_ONE_OPTION: string;
  COLLECTION_VALIDATION_NO_FIELD_ADDED: string;

  // COLLECTION_FILE_UPLOAD - File Upload
  COLLECTION_FILE_UPLOAD_LIMIT_MESSAGE: string;
  COLLECTION_FILE_ERROR_TOO_LARGE: string;

  // COLLECTION_EVALUATION - Evaluation System
  COLLECTION_EVALUATION_ERROR_INVALID: string;
  COLLECTION_EVALUATION_ERROR_PERMISSION_DENIED: string;
  COLLECTION_EVALUATION_ERROR_ALREADY_EVALUATED: string;

  // FIELD_TYPE_ADDITIONAL_LABELS - Additional Field Type Labels
  FIELD_TYPE_TEXT_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_SHOW_FILTER_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TRASH_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TRASH_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_DEFAULT_VALUE_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_DEFAULT_VALUE_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_OPTIONS_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_OPTIONS_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_OPTIONS_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_RELATIONSHIP_LIST_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_RELATIONSHIP_LIST_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_RELATIONSHIP_LIST_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_RELATIONSHIP_FIELD_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_RELATIONSHIP_FIELD_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_RELATIONSHIP_FIELD_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_ORDER_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_ORDER_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_ORDER_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TREE_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TREE_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_TREE_EMPTY_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_YES_OPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_NO_OPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_MANAGEMENT_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_MANAGEMENT_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_MANAGEMENT_EDIT_TOOLTIP: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_FIELD_MANAGEMENT_DRAG_TOOLTIP: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_CREATE_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_CREATE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_UPDATE_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_UPDATE_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_SHOW_TITLE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_SHOW_DESCRIPTION: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_ADD_BUTTON_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_FIELD_REQUIRED_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_AT_LEAST_ONE_OPTION_ERROR: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_SELECT_DATE_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_SELECT_TYPE_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_SELECT_OPTION_PLACEHOLDER: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_NO_FIELDS_ADDED_MESSAGE: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_UPLOAD_FILE_INSTRUCTIONS: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_UPLOAD_FILE_WAITING: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_SUPPORTED_FILES_LABEL: string;
  COLLECTION_ROUTE_SHEET_INTERNAL_REGISTER_FILE_SIZE_LIMIT: string;

  // LAYOUT_PROFILE - Profile Layout Components
  LAYOUT_PROFILE_AUTH_REQUIRED_ERROR: string;

  // LAYOUT_SIDEBAR - Sidebar Navigation
  LAYOUT_SIDEBAR_SETTINGS_TITLE: string;
  LAYOUT_SIDEBAR_AUTH_REQUIRED_ERROR: string;

  // COLLECTION_TOAST_OPERATIONS - Collection Toast Messages
  COLLECTION_TOAST_SENT_TO_TRASH: string;
  COLLECTION_TOAST_DELETED_PERMANENTLY: string;
  COLLECTION_TOAST_DELETED_PERMANENTLY_DESCRIPTION: string;
  COLLECTION_TOAST_UPDATED: string;

  // COLLECTION_DIALOG_OPERATIONS - Collection Dialog Messages
  COLLECTION_DIALOG_SEND_TO_TRASH_TITLE: string;
  COLLECTION_DIALOG_SEND_TO_TRASH_DESCRIPTION: string;
  COLLECTION_DIALOG_DELETE_TITLE: string;
  COLLECTION_DIALOG_DELETE_DESCRIPTION: string;

  // COLLECTION_ERROR_MESSAGES - Collection Error Messages
  COLLECTION_ERROR_AUTH_REQUIRED: string;
  COLLECTION_ERROR_CANNOT_TRASH_HAS_DATA: string;
  COLLECTION_ERROR_CANNOT_DELETE_HAS_RELATIONSHIPS: string;
  COLLECTION_ERROR_INVALID_CONFIGURATION: string;

  // COLLECTION_FILTER - Collection Filter Components
  COLLECTION_FILTER_COLLECTION_NAME: string;

  // COLLECTION_SHEET_FORM - Collection Form Components
  COLLECTION_SHEET_FORM_LOGO_LABEL: string;
  COLLECTION_SHEET_FORM_NAME_LABEL: string;
  COLLECTION_SHEET_FORM_DESCRIPTION_PLACEHOLDER: string;
  COLLECTION_SHEET_FORM_COLLABORATION_RESTRICTED_LABEL: string;
  COLLECTION_SHEET_FORM_COLLABORATION_OPEN_LABEL: string;

  // COLLECTION_CONFIGURATION - Collection Configuration
  COLLECTION_CONFIGURATION_LABEL: string;
};

export interface SystemSetting {
  LOCALE: "pt-br" | "en-us";
  FILE_UPLOAD_MAX_SIZE: string;
  FILE_UPLOAD_ACCEPTED: string[];
  FILE_UPLOAD_MAX_FILES_PER_UPLOAD: string;
  FILE_UPLOAD_PATH: string;
  PAGINATION_PER_PAGE: string;
  BASE_URL: string;
  DATABASE_URL: string;
  DATABASE_NAME: string;
  EMAIL_HOST: string;
  EMAIL_PORT: string;
  EMAIL_USER: string;
  EMAIL_PASSWORD: string;
  EMAIL_FROM: string;
}

// @ts-ignore
export enum TOKEN_STATUS {
  REQUESTED = "REQUESTED",
  EXPIRED = "EXPIRED",
  VALIDATED = "VALIDATED",
}

// @ts-ignore
export enum FIELD_TYPE {
  TEXT_SHORT = "TEXT_SHORT",
  TEXT_LONG = "TEXT_LONG",
  DROPDOWN = "DROPDOWN",
  DATE = "DATE",
  RELATIONSHIP = "RELATIONSHIP",
  FILE = "FILE",
  FIELD_GROUP = "FIELD_GROUP",
  REACTION = "REACTION",
  EVALUATION = "EVALUATION",
  CATEGORY = "CATEGORY",
}

// @ts-ignore
export enum FIELD_FORMAT {
  // TEXT_SHORT
  ALPHA_NUMERIC = "ALPHA_NUMERIC",
  INTEGER = "INTEGER",
  DECIMAL = "DECIMAL",
  URL = "URL",
  EMAIL = "EMAIL",

  // DATE
  DD_MM_YYYY = "dd/MM/yyyy",
  MM_DD_YYYY = "MM/dd/yyyy",
  YYYY_MM_DD = "yyyy/MM/dd",
  DD_MM_YYYY_HH_MM_SS = "dd/MM/yyyy HH:mm:ss",
  MM_DD_YYYY_HH_MM_SS = "MM/dd/yyyy HH:mm:ss",
  YYYY_MM_DD_HH_MM_SS = "yyyy/MM/dd HH:mm:ss",
  DD_MM_YYYY_DASH = "dd-MM-yyyy",
  MM_DD_YYYY_DASH = "MM-dd-yyyy",
  YYYY_MM_DD_DASH = "yyyy-MM-dd",
  DD_MM_YYYY_HH_MM_SS_DASH = "dd-MM-yyyy HH:mm:ss",
  MM_DD_YYYY_HH_MM_SS_DASH = "MM-dd-yyyy HH:mm:ss",
  YYYY_MM_DD_HH_MM_SS_DASH = "yyyy-MM-dd HH:mm:ss",
}

export interface Authenticated {
  sub: string;
  group: Pick<UserGroup, "name" | "description" | "slug">;
  permissions: string[];
  email: string;
  name: string;
}

export interface Base {
  _id: string;
  createdAt: string;
  updatedAt: string | null;
  trashedAt: string | null;
  trashed: boolean;
}

export interface ValidationToken extends Base {
  user: string;
  code: string;
  status: TOKEN_STATUS;
}

export interface Storage extends Base {
  url: string;
  filename: string;
  type: string;
  size: number;
  originalName: string;
}

export interface Permission extends Base {
  name: string;
  slug: string;
  description: string | null;
}

export interface UserGroup extends Base {
  name: string;
  slug: string;
  description: string | null;
  permissions: Permission[];
}

export interface User extends Base {
  name: string;
  email: string;
  password: string;
  status: "active" | "inactive";
  group: UserGroup;
}

export interface Schema {
  type: "Number" | "String" | "Date" | "Boolean" | "ObjectId";
  required?: boolean;
  ref?: string;
  default?: string | number | boolean | null;
}

export type CollectionSchema = Record<string, Schema | Schema[]>;

export interface Collection extends Base {
  _schema: CollectionSchema;
  name: string;
  description: string | null;
  logo: Storage | null;
  slug: string;
  fields: Field[];
  type: "collection" | "field-group";
  configuration: {
    style: "gallery" | "list";
    visibility: "public" | "restrict";
    collaboration: "open" | "restrict";
    administrators: User[];
    owner: User;
    fields: {
      orderList: string[];
      orderForm: string[];
    };
  };
}

export interface CollectionPayload {
  name: string;
  description: string | null;
  slug: string;
  type: "collection" | "field-group";
  _schema: CollectionSchema;
  logo: string | null;
  fields: string[];
  configuration: {
    style: "gallery" | "list";
    visibility: "public" | "restrict";
    collaboration: "open" | "restrict";
    administrators: string[];
    owner: string;
    fields: {
      orderList: string[];
      orderForm: string[];
    };
  };
}

export interface Category {
  id: string;
  label: string;
  children: Category[];
}

export interface FieldConfigurationRelationship {
  collection: Pick<Collection, "_id" | "slug">;
  field: Pick<Field, "_id" | "slug">;
  order: "asc" | "desc";
}

export type FieldConfigurationGroup = Pick<Collection, "_id" | "slug">;

export interface Field extends Base {
  name: string;
  slug: string;
  type: FIELD_TYPE;
  configuration: {
    required: boolean;
    multiple: boolean;
    format: FIELD_FORMAT | null;
    listing: boolean;
    filtering: boolean;
    defaultValue: string | null;
    relationship: FieldConfigurationRelationship | null;
    dropdown: string[] | null;
    category: Category[] | null;
    group: FieldConfigurationGroup | null;
  };
}

export interface Row extends Base, Record<string, any> {}

export interface Meta {
  total: number;
  page: number;
  perPage: number;
  lastPage: number;
  firstPage: number;
}
export interface Paginated<Entity> {
  data: Entity;
  meta: Meta;
}

export interface Reaction extends Base {
  user: User;
  type: "like" | "unlike";
}

export interface Evaluation extends Base {
  user: User;
  value: number;
}

export interface MenuRouteBaseItem {
  title: string;
  badge?: string;
  icon?: React.ElementType;
}

export type LinkItem = MenuRouteBaseItem & {
  url: LinkProps["to"];
  items?: never;
};

export type CollapsibleItem = MenuRouteBaseItem & {
  items: (MenuRouteBaseItem & { url: LinkProps["to"] })[];
  url?: LinkProps["to"];
};

export type MenuItem = CollapsibleItem | LinkItem;

export type MenuGroupItem = {
  title: string;
  items: MenuItem[];
};

export type MenuRoute = MenuGroupItem[];
