# LOCALE CONFIGURATIONS
LOCALE=en-us

# FILE UPLOAD CONFIGURATIONS
FILE_UPLOAD_MAX_SIZE=10485760
FILE_UPLOAD_ACCEPTED=jpg, jpeg, png, pdf, doc, docx, xls, xlsx, txt, zip, rar
FILE_UPLOAD_MAX_FILES_PER_UPLOAD=10

# PAGINATION CONFIGURATIONS
PAGINATION_PER_PAGE=20

DATABASE_URL=mongodb://local:local@127.0.0.1:27017
EMAIL_HOST=a
EMAIL_PORT=584
EMAIL_USER=a
EMAIL_PASSWORD=123234234234234