/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as PrivateLayoutRouteImport } from './../routes/_private/layout'
import { Route as AuthenticationLayoutRouteImport } from './../routes/_authentication/layout'
import { Route as AuthenticationIndexRouteImport } from './../routes/_authentication/index'
import { Route as RecoveryRequestCodeRouteImport } from './../routes/_recovery/request-code'
import { Route as PrivateSettingsRouteImport } from './../routes/_private/settings'
import { Route as PrivateProfileRouteImport } from './../routes/_private/profile'
import { Route as PrivateDashboardRouteImport } from './../routes/_private/dashboard'
import { Route as AuthenticationSignUpRouteImport } from './../routes/_authentication/sign-up'
import { Route as PublicTablesLayoutRouteImport } from './../routes/public/tables/layout'
import { Route as PrivateUsersIndexRouteImport } from './../routes/_private/users/index'
import { Route as PrivateUserGroupsIndexRouteImport } from './../routes/_private/user-groups/index'
import { Route as PrivateTablesIndexRouteImport } from './../routes/_private/tables/index'
import { Route as PrivateMenuManagementIndexRouteImport } from './../routes/_private/menu-management/index'
import { Route as PrivateTablesSlugLayoutRouteImport } from './../routes/_private/tables/$slug/layout'
import { Route as PublicTablesSlugIndexRouteImport } from './../routes/public/tables/$slug/index'
import { Route as PrivateTablesSlugIndexRouteImport } from './../routes/_private/tables/$slug/index'
import { Route as PrivatePagesSlugIndexRouteImport } from './../routes/_private/pages/$slug/index'
import { Route as PrivateTablesSlugRowsRowIdRouteImport } from './../routes/_private/tables/$slug/rows/$rowId'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLayoutRoute = AuthenticationLayoutRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticationLayoutRoute,
} as any)
const RecoveryRequestCodeRoute = RecoveryRequestCodeRouteImport.update({
  id: '/_recovery/request-code',
  path: '/request-code',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const AuthenticationSignUpRoute = AuthenticationSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthenticationLayoutRoute,
} as any)
const PublicTablesLayoutRoute = PublicTablesLayoutRouteImport.update({
  id: '/public/tables',
  path: '/public/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateUserGroupsIndexRoute = PrivateUserGroupsIndexRouteImport.update({
  id: '/user-groups/',
  path: '/user-groups/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateTablesIndexRoute = PrivateTablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateMenuManagementIndexRoute =
  PrivateMenuManagementIndexRouteImport.update({
    id: '/menu-management/',
    path: '/menu-management/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateTablesSlugLayoutRoute = PrivateTablesSlugLayoutRouteImport.update({
  id: '/tables/$slug',
  path: '/tables/$slug',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PublicTablesSlugIndexRoute = PublicTablesSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => PublicTablesLayoutRoute,
} as any)
const PrivateTablesSlugIndexRoute = PrivateTablesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateTablesSlugLayoutRoute,
} as any)
const PrivatePagesSlugIndexRoute = PrivatePagesSlugIndexRouteImport.update({
  id: '/pages/$slug/',
  path: '/pages/$slug/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateTablesSlugRowsRowIdRoute =
  PrivateTablesSlugRowsRowIdRouteImport.update({
    id: '/rows/$rowId',
    path: '/rows/$rowId',
    getParentRoute: () => PrivateTablesSlugLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/public/tables': typeof PublicTablesLayoutRouteWithChildren
  '/sign-up': typeof AuthenticationSignUpRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/profile': typeof PrivateProfileRoute
  '/settings': typeof PrivateSettingsRoute
  '/request-code': typeof RecoveryRequestCodeRoute
  '/': typeof AuthenticationIndexRoute
  '/tables/$slug': typeof PrivateTablesSlugLayoutRouteWithChildren
  '/menu-management': typeof PrivateMenuManagementIndexRoute
  '/tables': typeof PrivateTablesIndexRoute
  '/user-groups': typeof PrivateUserGroupsIndexRoute
  '/users': typeof PrivateUsersIndexRoute
  '/pages/$slug': typeof PrivatePagesSlugIndexRoute
  '/tables/$slug/': typeof PrivateTablesSlugIndexRoute
  '/public/tables/$slug': typeof PublicTablesSlugIndexRoute
  '/tables/$slug/rows/$rowId': typeof PrivateTablesSlugRowsRowIdRoute
}
export interface FileRoutesByTo {
  '/public/tables': typeof PublicTablesLayoutRouteWithChildren
  '/sign-up': typeof AuthenticationSignUpRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/profile': typeof PrivateProfileRoute
  '/settings': typeof PrivateSettingsRoute
  '/request-code': typeof RecoveryRequestCodeRoute
  '/': typeof AuthenticationIndexRoute
  '/menu-management': typeof PrivateMenuManagementIndexRoute
  '/tables': typeof PrivateTablesIndexRoute
  '/user-groups': typeof PrivateUserGroupsIndexRoute
  '/users': typeof PrivateUsersIndexRoute
  '/pages/$slug': typeof PrivatePagesSlugIndexRoute
  '/tables/$slug': typeof PrivateTablesSlugIndexRoute
  '/public/tables/$slug': typeof PublicTablesSlugIndexRoute
  '/tables/$slug/rows/$rowId': typeof PrivateTablesSlugRowsRowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authentication': typeof AuthenticationLayoutRouteWithChildren
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/public/tables': typeof PublicTablesLayoutRouteWithChildren
  '/_authentication/sign-up': typeof AuthenticationSignUpRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_recovery/request-code': typeof RecoveryRequestCodeRoute
  '/_authentication/': typeof AuthenticationIndexRoute
  '/_private/tables/$slug': typeof PrivateTablesSlugLayoutRouteWithChildren
  '/_private/menu-management/': typeof PrivateMenuManagementIndexRoute
  '/_private/tables/': typeof PrivateTablesIndexRoute
  '/_private/user-groups/': typeof PrivateUserGroupsIndexRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
  '/_private/pages/$slug/': typeof PrivatePagesSlugIndexRoute
  '/_private/tables/$slug/': typeof PrivateTablesSlugIndexRoute
  '/public/tables/$slug/': typeof PublicTablesSlugIndexRoute
  '/_private/tables/$slug/rows/$rowId': typeof PrivateTablesSlugRowsRowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/public/tables'
    | '/sign-up'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/request-code'
    | '/'
    | '/tables/$slug'
    | '/menu-management'
    | '/tables'
    | '/user-groups'
    | '/users'
    | '/pages/$slug'
    | '/tables/$slug/'
    | '/public/tables/$slug'
    | '/tables/$slug/rows/$rowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/public/tables'
    | '/sign-up'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/request-code'
    | '/'
    | '/menu-management'
    | '/tables'
    | '/user-groups'
    | '/users'
    | '/pages/$slug'
    | '/tables/$slug'
    | '/public/tables/$slug'
    | '/tables/$slug/rows/$rowId'
  id:
    | '__root__'
    | '/_authentication'
    | '/_private'
    | '/public/tables'
    | '/_authentication/sign-up'
    | '/_private/dashboard'
    | '/_private/profile'
    | '/_private/settings'
    | '/_recovery/request-code'
    | '/_authentication/'
    | '/_private/tables/$slug'
    | '/_private/menu-management/'
    | '/_private/tables/'
    | '/_private/user-groups/'
    | '/_private/users/'
    | '/_private/pages/$slug/'
    | '/_private/tables/$slug/'
    | '/public/tables/$slug/'
    | '/_private/tables/$slug/rows/$rowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticationLayoutRoute: typeof AuthenticationLayoutRouteWithChildren
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicTablesLayoutRoute: typeof PublicTablesLayoutRouteWithChildren
  RecoveryRequestCodeRoute: typeof RecoveryRequestCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/': {
      id: '/_authentication/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof AuthenticationLayoutRoute
    }
    '/_recovery/request-code': {
      id: '/_recovery/request-code'
      path: '/request-code'
      fullPath: '/request-code'
      preLoaderRoute: typeof RecoveryRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_authentication/sign-up': {
      id: '/_authentication/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpRouteImport
      parentRoute: typeof AuthenticationLayoutRoute
    }
    '/public/tables': {
      id: '/public/tables'
      path: '/public/tables'
      fullPath: '/public/tables'
      preLoaderRoute: typeof PublicTablesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/user-groups/': {
      id: '/_private/user-groups/'
      path: '/user-groups'
      fullPath: '/user-groups'
      preLoaderRoute: typeof PrivateUserGroupsIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/tables/': {
      id: '/_private/tables/'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof PrivateTablesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/menu-management/': {
      id: '/_private/menu-management/'
      path: '/menu-management'
      fullPath: '/menu-management'
      preLoaderRoute: typeof PrivateMenuManagementIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/tables/$slug': {
      id: '/_private/tables/$slug'
      path: '/tables/$slug'
      fullPath: '/tables/$slug'
      preLoaderRoute: typeof PrivateTablesSlugLayoutRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/public/tables/$slug/': {
      id: '/public/tables/$slug/'
      path: '/$slug'
      fullPath: '/public/tables/$slug'
      preLoaderRoute: typeof PublicTablesSlugIndexRouteImport
      parentRoute: typeof PublicTablesLayoutRoute
    }
    '/_private/tables/$slug/': {
      id: '/_private/tables/$slug/'
      path: '/'
      fullPath: '/tables/$slug/'
      preLoaderRoute: typeof PrivateTablesSlugIndexRouteImport
      parentRoute: typeof PrivateTablesSlugLayoutRoute
    }
    '/_private/pages/$slug/': {
      id: '/_private/pages/$slug/'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PrivatePagesSlugIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/tables/$slug/rows/$rowId': {
      id: '/_private/tables/$slug/rows/$rowId'
      path: '/rows/$rowId'
      fullPath: '/tables/$slug/rows/$rowId'
      preLoaderRoute: typeof PrivateTablesSlugRowsRowIdRouteImport
      parentRoute: typeof PrivateTablesSlugLayoutRoute
    }
  }
}

interface AuthenticationLayoutRouteChildren {
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

const AuthenticationLayoutRouteChildren: AuthenticationLayoutRouteChildren = {
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}

const AuthenticationLayoutRouteWithChildren =
  AuthenticationLayoutRoute._addFileChildren(AuthenticationLayoutRouteChildren)

interface PrivateTablesSlugLayoutRouteChildren {
  PrivateTablesSlugIndexRoute: typeof PrivateTablesSlugIndexRoute
  PrivateTablesSlugRowsRowIdRoute: typeof PrivateTablesSlugRowsRowIdRoute
}

const PrivateTablesSlugLayoutRouteChildren: PrivateTablesSlugLayoutRouteChildren =
  {
    PrivateTablesSlugIndexRoute: PrivateTablesSlugIndexRoute,
    PrivateTablesSlugRowsRowIdRoute: PrivateTablesSlugRowsRowIdRoute,
  }

const PrivateTablesSlugLayoutRouteWithChildren =
  PrivateTablesSlugLayoutRoute._addFileChildren(
    PrivateTablesSlugLayoutRouteChildren,
  )

interface PrivateLayoutRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateTablesSlugLayoutRoute: typeof PrivateTablesSlugLayoutRouteWithChildren
  PrivateMenuManagementIndexRoute: typeof PrivateMenuManagementIndexRoute
  PrivateTablesIndexRoute: typeof PrivateTablesIndexRoute
  PrivateUserGroupsIndexRoute: typeof PrivateUserGroupsIndexRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
  PrivatePagesSlugIndexRoute: typeof PrivatePagesSlugIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateTablesSlugLayoutRoute: PrivateTablesSlugLayoutRouteWithChildren,
  PrivateMenuManagementIndexRoute: PrivateMenuManagementIndexRoute,
  PrivateTablesIndexRoute: PrivateTablesIndexRoute,
  PrivateUserGroupsIndexRoute: PrivateUserGroupsIndexRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
  PrivatePagesSlugIndexRoute: PrivatePagesSlugIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicTablesLayoutRouteChildren {
  PublicTablesSlugIndexRoute: typeof PublicTablesSlugIndexRoute
}

const PublicTablesLayoutRouteChildren: PublicTablesLayoutRouteChildren = {
  PublicTablesSlugIndexRoute: PublicTablesSlugIndexRoute,
}

const PublicTablesLayoutRouteWithChildren =
  PublicTablesLayoutRoute._addFileChildren(PublicTablesLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticationLayoutRoute: AuthenticationLayoutRouteWithChildren,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicTablesLayoutRoute: PublicTablesLayoutRouteWithChildren,
  RecoveryRequestCodeRoute: RecoveryRequestCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
