name: Build and Test

on:
  push:
    branches: [develop, demo, intranet]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install API dependencies
        run: |
          cd api
          npm install

      - name: Build API
        run: |
          cd api
          npm run build

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install APP dependencies
        run: |
          cd app
          npm install

      - name: Build APP
        run: |
          cd app
          npm run build